sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 147hai147
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8xTHMDjNN3ReCMewX5
    access-key-secret: QlfX1d4hENAK9U8QtjkJcKEbjPZQBC
    bucket-name: haihai-sky-itcast
  redis:
    host: localhost
    port: 6379
    password: 147hai147
    database: 1
  wechat:
    appid: wx8a2b8e0a2ab2c1da
    secret: 7583ab0ffc0e6ce2748e77a1780f0cba
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl: