sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 147hai147
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8xTHMDjNN3ReCMewX5
    access-key-secret: QlfX1d4hENAK9U8QtjkJcKEbjPZQBC
    bucket-name: haihai-sky-itcast
  redis:
    host: localhost
    port: 6379
    password: 147hai147
    database: 1